---
name: "creating vpc and route tables"

on:
  # push:
  workflow_dispatch:

jobs:
  terraform_deploy:
    name: creating resources for vpc
    runs-on: ubuntu-22.04
    steps:
      - name: Checking Out
        uses: actions/checkout@v3

      - name: Configuring AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.TF_EC2_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.TF_EC2_SECRET_ACCESS_KEY }}"
          aws-region: ap-south-1

      - name: Setting up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform plan
        id: plan
        env:
          TF_VAR_ec2_name: "${{ github.event.inputs.ec2-name }}"
        run: |
          terraform init
          terraform validate
          terraform plan
        # terraform apply -auto-approve
