---
#
#  this method uses teraform inside github runner without using terraform cloud
#
name: "creating aws VPC resources without terrraform cloud"

on:
  # push:
  workflow_dispatch:

jobs:
  terraform_deploy:
    name: creating resources for vpc
    runs-on: ubuntu-22.04
    environment: test
    steps:
      - name: Checking Out
        uses: actions/checkout@v3

      - name: Configuring AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.TF_AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}"
          aws-region: ap-south-1

      - name: Setting up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform plan
        id: plan
        run: |
          terraform init
          terraform validate
          terraform plan

      - name: Terraform apply
        id: apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
