---
#
#  this method destroys the created resources
#
name: "destroying aws VPC resources without terrraform cloud"

on:
  workflow_dispatch:

jobs:
  cleanup:
    name: creating resources for vpc
    runs-on: ubuntu-22.04
    environment: test
    steps:
      - name: Checking Out
        uses: actions/checkout@v3

      - name: Configuring AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.TF_AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}"
          aws-region: ap-south-1

      - name: Setting up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform plan
        run: |
          terraform init

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve -input=false
